### ISSUE TITLE
3rd Party accessToken and tokenSecret configuration not as per documentation

### ISSUE THREAD

**Issue by darrenng-dpodium** [paypal/permissions-sdk-php#16] opened 2015-12-29 07:03 UTC
In documentation (https://github.com/paypal/sdk-core-php/wiki/Configuring-the-SDK) below configuration is shown:
acct3.UserName = certuser_biz_api1.paypal.com
acct3.Password = D6JNKKULHN3G5B8A
acct3.CertKey=password
acct3.CertPath=resource/sdk-cert.p12
acct3.AppId=APP-80W284485P519543T
acct3.accessToken = 'token from permissions API'
acct3.tokenSecret= 'token secret from permissions API'

However, upon tracking, in code level SDK reads for key {prefix}accessToken, eg:
acct3.UserName = certuser_biz_api1.paypal.com
acct3.Password = D6JNKKULHN3G5B8A
acct3.CertKey=password
acct3.CertPath=resource/sdk-cert.p12
acct3.AppId=APP-80W284485P519543T
acct3accessToken = 'token from permissions API'
acct3tokenSecret= 'token secret from permissions API'

**Comment by jaypatel512** [comment] 2017-03-24 19:40
Duplicate of https://github.com/paypal/sdk-core-php/issues/71

**Closed by jaypatel512** 2017-03-24 19:40 UTC
